enum ObjectTypeEnum {
    animals = "AN" ,
    astronomicalObjects = "AS",
    bookCollections = "BC",
    books = "BO",
    bookSeries = "BS",
    comics = "CC",
    conflicts = "CF",
    characters =  "CH",
    comicCollections = "CL",
    companies = "CO",
    comicSeries = "CS",
    comicStrips = "CT",
    elements = "EL",
    episodes = "EP",
    foods = " FO", 
    literaturePieces = "LI",
    locations = "LO", 
    magazines = "MA",
    medicalConditions = "ME", 
    movies= "MO",
    magazineSeries = "MS",
    materials = "MT",
    occupations = "OC",
    organizations = "OR",
    performers = "PE",
    seasons = "SA",
    spacecraftClasses = "SC",
    series = "SE",
    soundtracks = "SO",
    species = "SP", 
    spacecrafts = "SR",
    staffMembers = "ST",
    tradingCards = "TC",
    technologyPieces = "TE",
    titles = "TI",
    tradingCardDecks = "TR",
    tradingCardSets = "TS",
    videoGames = "VG",
    videoReleases = "VI",
    weapons = "WE"
}

export default ObjectTypeEnum;

